[CLIENT-7613] Update `constant-audio-level` warning.
twilio/twilio-client.js pull request #213
Opened 2020-08-25 19:12 UTC by mhuynh5757

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [CLIENT-7613](https://issues.corp.twilio.com/browse/CLIENT-7613)

### Description

This PR updates the `constant-audio-level` warning threshold to match the IDL as per CLIENT-7538.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2020-08-31 20:00 UTC, charliesantos commented on CHANGELOG.md
> +* The behavior for raising the `constant-audio-level` warning has been updated. Now, the most recent ten seconds of volume values are recorded and then analyzed. If the standard deviation of these sa
This entry should probably be under 1.12.4 (In Progress)

2020-08-31 20:05 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +const SAMPLE_COUNT_METRICS = 10;
Changing this to 10 affects how we calculate other metrics such as jitter, rtt, packets lost , and mos right? Since you are already adding `sampleCount` for audio levels in the `DEFAULT_THRESHOLDS`, we should probably keep this `SAMPLE_COUNT_METRICS` to 5.

2020-08-31 20:08 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> + * @param values The list of numbers to calculate the standard deviation from.
`@param sampleValues `, to match the actual parameter name. Or rename `sampleValues` to `values`, which ever you prefer.

2020-08-31 20:20 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +  ) / sampleValues.length;
What happens if length is zero in the case of no samples gathered?

2020-08-31 20:44 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +        this._raiseWarning(statName, 'maxDuration', { value: currentStreak });
It doesn't make sense to call this warning `maxDuration`, but we are calculating min standard deviation. I suggest we keep the calculations for limits.maxDuration as is. Then add a new threshold and call it minStandardDeviation. That means, in `DEFAULT_THRESHOLDS`, you will have something like

```
audioInputLevel: { minStandardDeviation: .01, maxValue: 32767 },
...
```

Then inside this same `_raiseWarningsForStat` function, you will have a different else block.
```
if (typeof limits.minStandardDeviation === 'number') {
// Do your stuff here
}
```

2020-10-01 23:23 UTC, charliesantos requested changes
Left a few comments. Also found some issues:
1) After constant audio input level warning is raised, it gets cleared right away after a few seconds. Try setting the audio input level to always zero.
2) I cannot get the constant audio **_output_** level warning to raise. Try setting the output level to zero.

2020-10-01 23:23 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +      const prevStreak: number = this._currentStreaks.get(statName) || 0;
Why are we still using streaks? We don't need this right?

2020-10-01 23:23 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +        this._raiseWarning(statName, 'minStandardDeviation', { value: currentStreak });
Why emitting the streak value? It should be the value of the calculated standard deviation no?

2020-10-01 23:23 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +        this._clearWarning(statName, 'minStandardDeviation', { value: prevStreak });
Why emitting the streak value? It should be the value of the calculated standard deviation no?

2020-10-02 21:26 UTC, mhuynh5757 commented
From this line https://github.com/twilio/twilio-client.js/blob/master/lib/twilio/connection.ts#L1077 it seems like we don't want to emit `constant-audio-output-level` warnings, do we want to change that?

2020-10-05 19:01 UTC, charliesantos approved these changes

2020-10-13 19:26 UTC, ryan-rowland requested changes
Found one line quirky but otherwise LGTM

2020-10-13 19:26 UTC, ryan-rowland commented on lib/twilio/statsMonitor.ts
> +  if (!(values.length > 0)) {
So in other words, `if (values.length <= 0)`? 😛

2020-10-13 19:28 UTC, ryan-rowland approved these changes

2020-10-15 17:09 UTC, merged