[CLIENT-7589] Update warning threshold for `packetsLostFraction`.
twilio/twilio-client.js pull request #220
Opened 2020-09-08 20:21 UTC by mhuynh5757

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [CLIENT-7589](https://issues.corp.twilio.com/browse/CLIENT-7589)

### Description

Update the warning threshold for `packetsLostFraction` to match the referenced IDL in the JIRA link.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [x] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2020-09-08 21:55 UTC, charliesantos requested changes
Left a few comments. Also found some issues:
1) Warning that is raised is `undefinedpacket-loss`
2) I don't see warning-cleared event.

Try mocking the [packetsLostFraction](https://github.com/twilio/twilio-client.js/blob/CLIENT-7589/lib/twilio/statsMonitor.ts#L334) value here during a call to really test it.

2020-09-08 21:55 UTC, charliesantos commented on CHANGELOG.md
> +* The behavior for raising the `high-packet-loss` warning has been updated. Now, the most recent seven seconds of packet-loss samples are recorded and analyzed. If the average of these samples is gre
Clear condition should be when average packet-loss over the most recent seven seconds falls to `1%` and below correct? Your statement suggests `< 1%`. But the condition should be `<= `%`

2020-09-08 21:55 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +    average: { max: { raise: 3, clear: 1 } },
Our conditions are getting complex. But I don't have a better suggestion so I think this will do..

2020-09-08 21:55 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +        raise: number;
Should we use `clearValue` and `raiseValue` instead? That way it's clear and consistent with how we use `raiseCount` and `clearCount` in `ThresholdOption` interface.

2020-09-08 21:55 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +function averageValues(values: number[]): number | null {
let's use `average` from `util.js`

2020-09-08 21:55 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +      const averageOption: Exclude<
nit: maybe just call this `option` or `config` so it reads better when you use it in this block. wdyt?

2020-09-08 21:55 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +      const valueAverage: number | null = averageValues(values);
nit: maybe just call this `average`?

2020-09-09 17:06 UTC, charliesantos requested changes
I think we should also add tests for warning names. See comments

2020-09-10 17:53 UTC, charliesantos requested changes

2020-09-10 17:53 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +    averageClearValue: 1,
`clearValue` should be ok no?

2020-09-10 17:53 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +        const newStreak: number = prevStreak + 1;
What's the purpose of getting/setting the streaks for min/max average?

2020-09-10 17:53 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +        const newStreak: number = prevStreak + 1;
We probably don't need them?

2020-09-10 17:53 UTC, charliesantos commented on lib/twilio/statsMonitor.ts
> +          this._raiseWarning(statName, thresholdName, { value: newStreak });
Instead of `{ value: newStreak }`, should we provide the average instead? `{ value: avg }`

2020-09-10 18:40 UTC, charliesantos approved these changes
Great work! +1

2020-09-21 16:37 UTC, ryan-rowland approved these changes

2020-09-21 17:26 UTC, merged