1.13.0 changelog
twilio/twilio-client.js pull request #235
Opened 2020-11-06 19:39 UTC by charliesantos

Changelog for 1.13.0. I also added documentation to wagtail. See drafts below. They will be live once we get green light from QE.

PreflightTest class: https://www.twilio.com/docs/admin/pages/22197/view_draft/
Device.testPreflight: https://www.twilio.com/docs/admin/pages/1773/view_draft/#testpreflight
Connection.on('warning'): https://www.twilio.com/docs/admin/pages/1772/view_draft/#onwarning-handlerwarningname-warningdata

2020-11-07 15:07 UTC, idelgado requested changes

2020-11-07 15:07 UTC, idelgado commented on CHANGELOG.md
> +const preflight = Device.testPreflight(token, options);
Didn't think of this when I read the docs originally but any concerns about having the word `test` in the method name or object name? The reason I ask is in some languages/IDEs that string has special meaning and could be misinterpreted. Though API wise it would still be beneficial to have a noun rather than just an adjective, an alternative could be `preflightCheck`.

2020-11-07 15:07 UTC, idelgado commented on CHANGELOG.md
> +```
Other than this code snippet is there something more demonstrable we could reference? Maybe the app?

2020-11-07 15:08 UTC, idelgado commented on CHANGELOG.md
> +```
I would expect the call to action to be, go try using this "quick deploy"...

2020-11-09 17:49 UTC, charliesantos commented on CHANGELOG.md
> +const preflight = Device.testPreflight(token, options);
I haven't come across IDEs that complains `test` is in the method or object name. Can you provide an example? I don't think this is a problem on JS. Will this be a problem on mobile?

Regarding API name, API wise, I think the current convention (testFoo) makes sense. We usually name methods starting with a verb since it indicates that it will do some action. Noun is usually for class names no?

2020-11-09 17:49 UTC, charliesantos commented on CHANGELOG.md
> +```
Good point on the quickstart app. I will link it in the changelog.

2020-11-09 18:02 UTC, charliesantos commented on CHANGELOG.md
> +const preflight = Device.testPreflight(token, options);
I think we should use `verbNoun` convention. I was just talking to @ryan-rowland , what do you think about `Device.runPreflightTest`?

2020-11-09 18:05 UTC, charliesantos commented on CHANGELOG.md
> +const preflight = Device.testPreflight(token, options);
If we end up renaming this, I have a little concern on RTC Diagnostics where we named all our tests using this convention. And that is already GA :(
```
testAudioInputDevice
testAudioOutputDevice
testMediaConnectionBitrate
testVideoInputDevice
```

2020-11-09 18:08 UTC, charliesantos commented on CHANGELOG.md
> +```
I added a link to the API docs and quick deploy app. The API doc link is not live yet, but you can view the draft here. https://www.twilio.com/docs/admin/pages/22197/view_draft/

2020-11-09 22:31 UTC, idelgado commented on CHANGELOG.md
> +const preflight = Device.testPreflight(token, options);
How about just `runPreflight`? It's not actually a test as in it does not use a test unit framework. Might be better to use a more general naming convention for the interface.

2020-11-10 15:44 UTC, idelgado approved these changes
Please make sure to update the IDL in addition to making the change here.

2020-11-10 15:44 UTC, idelgado commented on CHANGELOG.md
> +### Voice diagnostics using PreflightTest API
> using runPreflight API

2020-11-10 19:44 UTC, ryan-rowland approved these changes

2020-11-10 20:06 UTC, merged