[CLIENT-7730] Allow Connection specific ICE Servers
twilio/twilio-client.js pull request #245
Opened 2021-01-06 17:08 UTC by mhuynh5757

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [CLIENT-7730](https://issues.corp.twilio.com/browse/CLIENT-7730)

### Description

Introduces a new parameter for `Device.connect` and `Connection.accept` to allow for `Connection` specific ICE Servers.

## Burndown

### Before review
* [x] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2021-01-06 18:28 UTC, ryan-rowland requested changes
The implementation looks clean. Had one question though.

2021-01-06 18:28 UTC, ryan-rowland commented on CHANGELOG.md
> +Passing the `iceServers` parameter to these functions will override any previously set `iceServers` within `Device.options.rtcConfiguration` but not affect any other members set within `Device.option
Should we allow all of the members to be changed? What are they exactly?

2021-01-06 21:29 UTC, mhuynh5757 commented on CHANGELOG.md
> +Passing the `iceServers` parameter to these functions will override any previously set `iceServers` within `Device.options.rtcConfiguration` but not affect any other members set within `Device.option
The whole typedef is as follows:
```
interface RTCConfiguration {
    bundlePolicy?: RTCBundlePolicy;
    certificates?: RTCCertificate[];
    iceCandidatePoolSize?: number;
    iceServers?: RTCIceServer[];
    iceTransportPolicy?: RTCIceTransportPolicy;
    peerIdentity?: string;
    rtcpMuxPolicy?: RTCRtcpMuxPolicy;
}
```
I was unsure about this one as well considering we pass the whole `RTCConfiguration` to the `PeerConnection`.

2021-01-13 18:13 UTC, ryan-rowland requested changes
The implementation looks good, I think we just need to bump to 1.14.0 and we should be good to merge.

2021-01-13 18:13 UTC, ryan-rowland commented on CHANGELOG.md
> +1.13.2 (In Progress)
New feature should bump this to 1.14.0 yeah?

2021-01-13 18:23 UTC, ryan-rowland approved these changes

2021-01-13 20:10 UTC, merged