[CLIENT-8268] Remove options for sane defaults.
twilio/twilio-client.js pull request #254
Opened 2021-02-12 21:44 UTC by mhuynh5757

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [CLIENT-8268](https://issues.corp.twilio.com/browse/CLIENT-8268)

### Description

This PR removes deprecated `Device` options for sane defaults as part of `twilio-client.js@2.x`.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2021-02-24 20:19 UTC, ryan-rowland requested changes

2021-02-24 20:19 UTC, ryan-rowland commented on CHANGELOG.md
> +```
We're also removing:

- audioConstraints (moving to accept/connect)
- debug (wasn't this removed as part of loglevel?)
- dscp (this can go inside rtcConfiguration)
- region (replaced by edge)
- rtcConfiguration (moving to accept/connect)
- warnings (wasn't this removed as part of loglevel?)

I'm currently removing audioConstraints and rtcConfiguration in my PR, so you can ignore those, but the rest should be removed as part of this PR I think.

2021-02-25 17:41 UTC, mhuynh5757 commented on CHANGELOG.md
> +```
In another discussion, this PR will address item 4 in this doc: https://docs.google.com/document/d/1qT5mSdw45NRQLijx-KBgfayVZScVKCaKQusUybMbJac/edit#

2021-02-25 19:11 UTC, ryan-rowland approved these changes

2021-02-25 20:47 UTC, merged